name: JobStride CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: phasetherapper
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend image
      run: |
        docker build -t phasetherapper/jobstride-frontend:latest ./frontend
        docker push phasetherapper/jobstride-frontend:latest

    - name: Build and push backend image
      run: |
        docker build -t phasetherapper/jobstride-backend:latest ./backend
        docker push phasetherapper/jobstride-backend:latest

    - name: Complete
      run: echo "✅ Docker images pushed to Docker Hub"