name: JobStride CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build frontend
      run: |
        cd frontend
        docker build -t jobstride-frontend .

    - name: Build backend
      run: |
        cd backend
        docker build -t jobstride-backend .

    # Optional: Add tests here

    - name: Complete
      run: echo "✅ CI pipeline finished"